import { rest } from "msw";

const data = {
  1: {
    accountName: "생활비",
    accountNumber: "70-123-4567",
    accountBalance: "200000",
    piggyBank: {
      아이패드: {
        plan: "50000",
        current: "25000",
      },
      에어팟: {
        plan: "200000",
        current: "50000",
      },
      모니터: {
        plan: "230000",
        current: "30000",
      },
      스피커: {
        plan: "120000",
        current: "64000",
      },
    },
    log: [
      {
        date: "2021-09-26",
        income: "out",
        classify: "shopping",
        history: "11번가",
        price: 70700,
      },
      {
        date: "2021-09-29",
        income: "out",
        classify: "eatout",
        history: "김밥천국",
        price: 6000,
      },
      {
        date: "2021-09-29",
        income: "out",
        classify: "shopping",
        history: "알라딘",
        price: 62000,
      },
      {
        date: "2021-09-29",
        income: "in",
        classify: "",
        history: "국민지원금",
        price: 250000,
      },
      {
        date: "2021-09-30",
        income: "out",
        classify: "mart",
        history: "이마트",
        price: 99999,
      },
      {
        date: "2021-09-30",
        income: "out",
        classify: "shopping",
        history: "교보문고",
        price: 25000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "eatout",
        history: "더파크뷰",
        price: 195000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "shopping",
        history: "JARA",
        price: 59000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "eatout",
        history: "파스퇴르",
        price: 7000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "shopping",
        history: "젤네일",
        price: 115000,
      },
      {
        date: "2021-10-02",
        income: "in",
        classify: "",
        history: "아프리카TV",
        price: 236000,
      },
      {
        date: "2021-10-02",
        income: "out",
        classify: "shopping",
        history: "블루투스 마우스",
        price: 116000,
      },
      {
        date: "2021-10-02",
        income: "out",
        classify: "eatout",
        history: "아웃백 스테이크하우스",
        price: 114000,
      },
      {
        date: "2021-10-03",
        income: "in",
        classify: "",
        history: "업비트",
        price: 370000,
      },
      {
        date: "2021-10-03",
        income: "out",
        classify: "mart",
        history: "Costco",
        price: 135000,
      },
      {
        date: "2021-09-01",
        income: "out",
        classify: "mart",
        history: "이마트",
        price: 36000,
      },
    ],
  },
  2: {
    accountName: "용돈",
    accountNumber: "70-123-4567",
    accountBalance: "200000",
    piggyBank: {
      아이패드: {
        plan: "50000",
        current: "25000",
      },
      에어팟: {
        plan: "200000",
        current: "50000",
      },
      모니터: {
        plan: "230000",
        current: "30000",
      },
      스피커: {
        plan: "120000",
        current: "64000",
      },
    },
    log: [
      {
        date: "2021-09-26",
        income: "out",
        classify: "shopping",
        history: "11번가",
        price: 70700,
      },
      {
        date: "2021-09-29",
        income: "out",
        classify: "eatout",
        history: "김밥천국",
        price: 6000,
      },
      {
        date: "2021-09-29",
        income: "out",
        classify: "shopping",
        history: "알라딘",
        price: 62000,
      },
      {
        date: "2021-09-29",
        income: "in",
        classify: "",
        history: "국민지원금",
        price: 250000,
      },
      {
        date: "2021-09-30",
        income: "out",
        classify: "mart",
        history: "이마트",
        price: 99999,
      },
      {
        date: "2021-09-30",
        income: "out",
        classify: "shopping",
        history: "교보문고",
        price: 25000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "eatout",
        history: "더파크뷰",
        price: 195000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "shopping",
        history: "JARA",
        price: 59000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "eatout",
        history: "파스퇴르",
        price: 7000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "shopping",
        history: "젤네일",
        price: 115000,
      },
      {
        date: "2021-10-02",
        income: "in",
        classify: "",
        history: "아프리카TV",
        price: 236000,
      },
      {
        date: "2021-10-02",
        income: "out",
        classify: "shopping",
        history: "블루투스 마우스",
        price: 116000,
      },
      {
        date: "2021-10-02",
        income: "out",
        classify: "eatout",
        history: "아웃백 스테이크하우스",
        price: 114000,
      },
      {
        date: "2021-10-03",
        income: "in",
        classify: "",
        history: "업비트",
        price: 370000,
      },
      {
        date: "2021-10-03",
        income: "out",
        classify: "mart",
        history: "Costco",
        price: 135000,
      },
      {
        date: "2021-09-01",
        income: "out",
        classify: "mart",
        history: "이마트",
        price: 36000,
      },
    ],
  },
  3: {
    accountName: "집사기",
    accountNumber: "70-123-4567",
    accountBalance: "200000",
    piggyBank: {
      아이패드: {
        plan: "50000",
        current: "25000",
      },
      에어팟: {
        plan: "200000",
        current: "50000",
      },
      모니터: {
        plan: "230000",
        current: "30000",
      },
      스피커: {
        plan: "120000",
        current: "64000",
      },
    },
    log: [
      {
        date: "2021-09-26",
        income: "out",
        classify: "shopping",
        history: "11번가",
        price: 70700,
      },
      {
        date: "2021-09-29",
        income: "out",
        classify: "eatout",
        history: "김밥천국",
        price: 6000,
      },
      {
        date: "2021-09-29",
        income: "out",
        classify: "shopping",
        history: "알라딘",
        price: 62000,
      },
      {
        date: "2021-09-29",
        income: "in",
        classify: "",
        history: "국민지원금",
        price: 250000,
      },
      {
        date: "2021-09-30",
        income: "out",
        classify: "mart",
        history: "이마트",
        price: 99999,
      },
      {
        date: "2021-09-30",
        income: "out",
        classify: "shopping",
        history: "교보문고",
        price: 25000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "eatout",
        history: "더파크뷰",
        price: 195000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "shopping",
        history: "JARA",
        price: 59000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "eatout",
        history: "파스퇴르",
        price: 7000,
      },
      {
        date: "2021-10-01",
        income: "out",
        classify: "shopping",
        history: "젤네일",
        price: 115000,
      },
      {
        date: "2021-10-02",
        income: "in",
        classify: "",
        history: "아프리카TV",
        price: 236000,
      },
      {
        date: "2021-10-02",
        income: "out",
        classify: "shopping",
        history: "블루투스 마우스",
        price: 116000,
      },
      {
        date: "2021-10-02",
        income: "out",
        classify: "eatout",
        history: "아웃백 스테이크하우스",
        price: 114000,
      },
      {
        date: "2021-10-03",
        income: "in",
        classify: "",
        history: "업비트",
        price: 370000,
      },
      {
        date: "2021-10-03",
        income: "out",
        classify: "mart",
        history: "Costco",
        price: 135000,
      },
      {
        date: "2021-09-01",
        income: "out",
        classify: "mart",
        history: "이마트",
        price: 36000,
      },
    ],
  },
};

export const handler = [
  rest.get("/:id", (req, res, ctx) => {
    const postId = req.params.id;
    return res(ctx.status(200), ctx.json(data[postId]));
  }),
];
